todo/urls.py
from django.urls import path
from .views import TodoDelete, TodoList, TodoDetail, TodoCreate, TodoUpdate

urlpatterns = [
    path("list/", TodoList.as_view(), name="list"),
    path("detail/<int:pk>", TodoDetail.as_view(), name="detail"),
    path("create/", TodoCreate.as_view(), name="create"),
    path("delete/<int:pk>", TodoDelete.as_view(), name="delete"),
    path("update/<int:pk>", TodoUpdate.as_view(), name="update"),
]

todoproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path("admin/", admin.site.urls), path("", include("todo.urls"))]

todo/models.py
from random import choices
from django.db import models

# Create your models here.

CHOICE = (("danger", "high"), ("warning", "normal"), ("info", "low"))

class TodoModel(models.Model):
    title = models.CharField(max_length=100)
    memo = models.TextField()
    priority = models.CharField(max_length=50, choices=CHOICE)
    deadline= models.DateField()

    def __str__(self):
        return self.title

todo/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

from todo.models import TodoModel

# Create your views here.


class TodoList(ListView):
    template_name: str = "list.html"
    model = TodoModel

class TodoDetail(DetailView):
    template_name: str = 'detail.html'
    model = TodoModel

class TodoCreate(CreateView):
    template_name: str = 'create.html'
    model = TodoModel
    fields = ('title', 'memo', 'priority', 'deadline')
    success_url = reverse_lazy('list')

class TodoDelete(DeleteView):
    template_name: str = 'delete.html'
    model = TodoModel
    success_url = reverse_lazy('list')

class TodoUpdate(UpdateView):
    template_name: str = 'update.html'
    model = TodoModel
    fields = {'title', 'memo', 'priority', 'deadline'}
    success_url = reverse_lazy('list')

templates/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />

    <title>{% block page_header %} {% endblock page_header %}</title>
  </head>
  <body>
    <header class="border-bottom">
      <div class="container d-flex align-items-center justify-content-between">
        <h1 class="fs-3 my-3"><a href="{% url 'list' %}" class="text-reset text-decoration-none">TODO LIST</a></h1>
        <a class="btn btn-outline-primary" href="{% url 'create' %}" aria-label="TODOタスクを作成する">
          作成
        </a>
      </div>
    </header>
    {% block content %} {% endblock content %}
  </body>
</html>

templates/create.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block page_header %} Create Page {% endblock page_header %}

{% block content %}
<div class="container pt-4">
    <form action="" method="POST">{% csrf_token %}
        <div class="mb-5">
            <div class="mb-3">
                <label for="id_title" class="form-label">タイトル</label>
                {{ form.title|add_class:"form-control" }}
            </div>
            <div class="mb-3">
                <label for="id_memo" class="form-label">メモ</label>
                {{ form.memo|add_class:"form-control" }}
            </div>
            <div class="mb-3">
                <label for="id_priority" class="form-label">優先度</label>
                {{ form.priority|add_class:"form-select" }}
            </div>
            <div>
                <label for="id_deadline" class="form-label">期限</label>
                {{ form.deadline|add_class:"form-control" }}
            </div>
        </div>
        <input type="submit" value="作成" class="btn btn-primary">
    </form>
</div>
{% endblock content %}

templates/delete.html
{% extends 'base.html' %}

{% block page_header %} Delete Page {% endblock page_header %}

{% block content %}
<div class="container pt-4">
    {{object.title}}
    <form action="" method="POST">{% csrf_token %}
        <input type="submit" value="削除" class="btn btn-danger">
    </form>
</div>
{% endblock content %}

templates/detail.html
{% extends 'base.html' %}

{% block page_header %}{{ object.title }} - Detail Page {% endblock page_header %}

{% block content %}
<div class="container pt-4">
  <a href="{% url 'list' %}" class="text-decoration-none">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
    </svg>
    一覧へ
  </a>

  <div class="mt-5">
    <dl>
      <div class="mb-3">
        <dt class="text-muted">タイトル</dt>
        <dd class="fs-4 text-break">{{ object.title }}</dd>
      </div>
      <div class="mb-3">
        <dt class="text-muted">メモ</dt>
        <dd class="fs-5 text-break">{{ object.memo }}</dd>
      </div>
      <div class="mb-3">
        <dt class="text-muted">優先度</dt>
        <dd class="fs-5 text-break">
          {% if object.priority == 'danger' %}
              高
          {% elif object.priority == 'warning' %}
              中
          {% else %}
              低
          {% endif %}
        </dd>
      </div>
      <div class="mb-3">
        <dt class="text-muted">期限</dt>
        <dd class="fs-5 text-break">{{ object.deadline | date:"Y年n月j日" }}</dd>
      </div>
    </dl>
  </div>
</div>
{% endblock content %}

templates/list.html
{% extends 'base.html' %}

{% block page_header %} List Page {% endblock page_header %}

{% block content %}
<div class="container pt-4">
    <ul class="list-group list-group-flush">
        {% for item in object_list %}
        <li class="d-flex align-items-center list-group-item">
            <div class="flex-fill d-flex align-items-center gap-2">
                <span class="badge bg-{{ item.priority }}">
                    {% if item.priority == 'danger' %}
                        高
                    {% elif item.priority == 'warning' %}
                        中
                    {% else %}
                        低
                    {% endif %}
                </span>
                <div class="flex-fill">
                    <p class="text-muted m-0">期限：{{ item.deadline|date:"Y/m/d" }}</p>
                    <p class="m-0 fs-5">{{ item.title }}</p>
                </div>
            </div>
            <ul class="d-flex gap-2 list-unstyled">
                <li>
                    <a class="btn btn-primary btn-sm" href="{% url 'detail' item.pk %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16">
                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                            <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                        </svg>
                        詳細
                    </a>
                </li>
                <li>
                    <a class="btn btn-success btn-sm" href="{% url 'update' item.pk %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                            <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                        </svg>
                        編集
                    </a>
                </li>
                <li>
                    <a class="btn btn-danger btn-sm" href="{% url 'delete' item.pk %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                        </svg>
                        削除
                    </a>
                </li>
            </ul>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

templates/update.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block page_header %} Update Page {% endblock page_header %}

{% block content %}
<div class="container pt-4">
    <form action="" method="POST">{% csrf_token %}
        <div class="mb-5">
            <div class="mb-3">
                <label for="id_title" class="form-label">タイトル</label>
                {{ form.title|add_class:"form-control" }}
            </div>
            <div class="mb-3">
                <label for="id_memo" class="form-label">メモ</label>
                {{ form.memo|add_class:"form-control" }}
            </div>
            <div class="mb-3">
                <label for="id_priority" class="form-label">優先度</label>
                {{ form.priority|add_class:"form-select" }}
            </div>
            <div>
                <label for="id_deadline" class="form-label">期限</label>
                {{ form.deadline|add_class:"form-control" }}
            </div>
        </div>
        <input type="submit" value="更新" class="btn btn-primary">
    </form>
</div>
{% endblock content %}